const DATA_FETCHING_STARTED = "DATA_FETCHING_STARTED";
const DATA_FETCHING_FAILED = "DATA_FETCHING_FAILED";
const DATA_FETCHING_SUCCESS = "DATA_FETCHING_SUCCESS";

export {
  DATA_FETCHING_STARTED,
  DATA_FETCHING_FAILED,
  DATA_FETCHING_SUCCESS,
};