const DATA_FETCHING_STARTED = "DATA_FETCHING_STARTED";
const DATA_FETCHING_FAILED = "DATA_FETCHING_FAILED";
const DATA_FETCHING_SUCCESS = "DATA_FETCHING_SUCCESS";
const DELETE_ITEM = "DELETE_ITEM";
const SVUOTA_CARRELLO = "SVUOTA_CARRELLO";
const AUMENTA_QTY='AUMENTA_QTY';
const DIMINUISCI_QTY='DIMINUISCI_QTY';

export {
  DATA_FETCHING_STARTED,
  DATA_FETCHING_FAILED,
  DATA_FETCHING_SUCCESS,
  DELETE_ITEM,
  SVUOTA_CARRELLO,
  AUMENTA_QTY,
  DIMINUISCI_QTY,
};